### ISSUE TITLE
[Code Refraction ] Change the file type from jsx to tsx 

### ISSUE THREAD

**Issue by yasharth291** [Incentive-Coders/camprec#6]
- **Issue Description:** 
The file type of every file should be changed to tsx and all the coming errors should be removed.

- **Issue Severity:** 
High

**Comment by nikhil12377** [comment]
I'm interested.

**Comment by rupalisingh** [comment]
Hi, I am interested.

**Comment by Amanmawar17** [comment]
i'm interested
